### ISSUE TITLE
GPU Compute Capability below 8.0

### ISSUE THREAD

**Issue by siosda** [SUC-DriverOld/MSST-WebUI#16]
日志信息如下 
似乎是 GPU计算能力低于8.0,无法使用GPU加速, 我使用的是1066 算力6.1 已更新最新版驱动,不确定我这个情况是否为个例 或是我使用方式有问题
只尝试了model_bs_roformer_ep_368_sdr_12.9628模型 其它未知
附上一张算力表 文档中似乎没提过对算力的要求 可以完善一下

[INFO] 正在启动WebUI, 请稍等...
[INFO] Starting WebUI, please wait...
[INFO] 若启动失败, 请尝试删除软件根目录下data文件夹或以管理员身份运行
[INFO] If launch failed, try to delete the data folder under the root directory or run as administrator
[注意] WebUI运行过程中请勿关闭此窗口!
[NOTE] Do not close this window while WebUI is running!
[INFO] 设备信息：0: NVIDIA GeForce GTX 1060 6GB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Use command: .\workenv\python.exe msst_inference.py --model_type bs_roformer --config_path "configs/viperx/model_bs_roformer_ep_368_sdr_12.9628.yaml" --start_check_point "pretrain/vocal_models\model_bs_roformer_ep_368_sdr_12.9628.ckpt" --input_folder "temp" --store_dir "C:/Users" --device_ids 0
**23:37:47.240 [INFO] msst_inference - Using device: cuda:0
GPU Compute Capability below 8.0, using math or mem efficient attention if input tensor is on cuda**
23:37:48.531 [INFO] msst_inference - Start from checkpoint: pretrain/vocal_models\model_bs_roformer_ep_368_sdr_12.9628.ckpt
23:37:49.390 [INFO] msst_inference - Instruments: ['vocals', 'instrumental']
23:37:49.588 [INFO] msst_inference - Total files found: 1
![Compute Capability](https://github.com/user-attachments/assets/7bec6de3-3190-4bac-a165-44d1e0b0043a)

**Comment by SUC-DriverOld** [comment]
正常现象，A100以下的显卡都是低于8.0的，不会影响gpu加速，只不过高于8.0有新的加速方式罢了。如果一首歌处理时间不超过10分钟都是正常的

**Comment by SUC-DriverOld** [comment]
不过，此项目的显卡算力是根据A100来进行划分的，理论上低于A100的显卡都会有这个提示
