### ISSUE TITLE
How about add Kim mel roformer? 

### ISSUE THREAD

**Issue by hundrix** [SUC-DriverOld/MSST-WebUI#19]
Since this is one of the best vocal models, how about add it to the model list? 

https://github.com/KimberleyJensen/Mel-Band-Roformer-Vocal-Model

**Comment by SUC-DriverOld** [comment]
It has been added in version 1.5， however the name of the model in the program is called “model_vocals_mel_band_roformer_kj_sdr_10.98.ckpt（Kim_mel_band_roformer）”. Therefore, some people may not be able to find this model. I will consider changing the model name in future version.
Besides， if you use version 1.6 preview， you can add models in “webui-settings-install unofficial msst midel”.

**Comment by hundrix** [comment]
Thanks for the great project. I've replaced UVR with MSST in my workflow as the first step for cleaning live stream recordings, specifically for RVC training. The following preset gets the job done effectively:

model_bs_roformer_ep_317_sdr_12.9755.ckpt
model_mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt
deverb_bs_roformer_8_256dim_8depth.ckpt
denoise_mel_band_roformer_aufr33_sdr_27.9959.ckpt
