### ISSUE TITLE
源码webui.py似乎有问题

### ISSUE THREAD

**Issue by Sakura-Hydrangea** [SUC-DriverOld/MSST-WebUI#20]
![屏幕截图 2024-09-13 125716](https://github.com/user-attachments/assets/d50b8d74-7323-4161-9164-b9a017ef29aa)

**Comment by SUC-DriverOld** [comment]
感谢您的提出！我已修复此错误 [#commit 105](https://github.com/SUC-DriverOld/MSST-WebUI/commit/972969a4cd11d26dc843358f9b5bffcd63e4e441)
犯低级错误了，非常抱歉！
