### ISSUE TITLE
复选框内组件差距

### ISSUE THREAD

**Issue by Sakura-Hydrangea** [SUC-DriverOld/MSST-WebUI#22]
![470ac1e532b582193f1ead7a3f3c95c](https://github.com/user-attachments/assets/34e7425e-1a22-43e1-b2bd-5c302a3c62b1)
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/3a7ff4fe-81b0-4d9d-832c-ee2227aededb">
为什么b站视频内的复选框有更多的小组件，在源码中似乎没有找到这些组件

**Comment by SUC-DriverOld** [comment]
这是gr.Audio自带的功能，自1.5版本起，由于使用gr.Audio会导致非wav文件文件名错误的问题，已经改用gr.File和gr.Files，所以会少组建

**Comment by SUC-DriverOld** [comment]
此外，1.6.1版本支持上传多个音频文件进行处理，所以导致gr.Audio彻底放弃使用，改为gr.Files
