### ISSUE TITLE
请求在小工具里增加歌曲BPM计算功能

### ISSUE THREAD

**Issue by Kingstom8MB** [SUC-DriverOld/MSST-WebUI#27]
RT，用UVR5和MSST分离了很多伴奏，有一次想做一个混剪，但是BPM计算工具没有找到本地的，想问一下UP方便时候可以做一个吗，这样子不用开太多网页，用起来也方便

**Comment by SUC-DriverOld** [comment]
去使用MixMeister BPM Analyzer这个软件。之前有尝试过添加bpm分析，出来的结果准确率太低了。

**Comment by Kingstom8MB** [comment]
谢了
