### ISSUE TITLE
recent update cause colab run err

### ISSUE THREAD

**Issue by ywaby** [SUC-DriverOld/MSST-WebUI#29]
### Your operating environment
colab

### How to reproduce
run all

### Provide log here (optional)

info
```
/content/MSST-WebUI
Traceback (most recent call last):
  File "/content/MSST-WebUI/tools/webUI_for_clouds/webUI_for_clouds.py", line 7, in <module>
    from utils.constant import *
ModuleNotFoundError: No module named 'utils'
```

**Comment by SUC-DriverOld** [comment]
I fix these bugs in the last commits and it works now. Please upgrade `webUI_for_colab.ipynb` and the whole codes and try again. Thank you for your feedback.
![20241108164257](https://github.com/user-attachments/assets/903d3362-c5b9-464a-bfd3-c93cfda96f6f)

**Comment by ywaby** [comment]
it fixed
