### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocess

### ISSUE THREAD

**Issue by iworldtong** [SUC-DriverOld/MSST-WebUI#30]
在ubuntu上部署，出现问题：
17:18:56.905 [DEBUG] [webui/msst.py:94] Saved MSST inference config: {'model_type': 'vocal_models', 'selected_model': 'model_bs_roformer_ep_368_sdr_12.9628.ckpt', 'input_dir': None, 'store_dir': '/home//software/datasets/audios/t/mss_output', 'device': ['0: NVIDIA A800 80GB PCIe'], 'output_format': 'wav', 'force_cpu': False, 'instrumental': [], 'use_tta': True, 'preset': None, 'preset_use_tta': False, 'extra_output_dir': False, 'vr_select_model': None, 'vr_window_size': 512, 'vr_aggression': 5, 'vr_batch_size': 2, 'vr_primary_stem_only': False, 'vr_secondary_stem_only': False, 'vr_post_process_threshold': 0.2, 'vr_invert_spect': False, 'vr_enable_tta': False, 'vr_high_end_process': False, 'vr_enable_post_process': False}
17:18:56.941 [WARNING] [webui/msst.py:152] No selected instruments, extract all instruments to /home//software/datasets/audios/t/mss_output
17:18:56.941 [INFO] [webui/msst.py:158] Starting MSST inference process...
17:18:56.965 [DEBUG] [webui/msst.py:168] Inference process started, PID: 3278499
17:18:56.968 [DEBUG] [webui/msst.py:182] Start MSST inference process with parameters: model_type=bs_roformer, config_path=configs/vocal_models/model_bs_roformer_ep_368_sdr_12.9628.yaml, model_path=pretrain/vocal_models/model_bs_roformer_ep_368_sdr_12.9628.ckpt, device=auto, gpu_ids=[0], output_format=wav, use_tta=True, store_dict={'vocals': '/home//software/datasets/audios/t/mss_output', 'instrumental': '/home//software/datasets/audios/t/mss_output'}, debug=True, input_folder=tmpdir
17:18:56.970 [DEBUG] [inference/msst_infer.py:88] Operating System: Linux #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024
17:18:56.973 [DEBUG] [inference/msst_infer.py:91] Python Version: 3.10.15
17:18:56.974 [DEBUG] [inference/msst_infer.py:94] PyTorch Version: 2.5.1
17:18:58.108 [DEBUG] [inference/msst_infer.py:100] FFmpeg installed: ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
17:18:58.109 [DEBUG] [inference/msst_infer.py:63] CUDA is available in Torch, setting Torch device to CUDA
17:18:58.111 [INFO] [inference/msst_infer.py:72] Using device: cuda:0, device_ids: [0]
17:19:01.325 [ERROR] [webui/msst.py:203] Separation failed: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
Traceback (most recent call last):
  File "/home//software/codes/MSST-WebUI/webui/msst.py", line 185, in run_inference
    separator = MSSeparator(
  File "/home//software/codes/MSST-WebUI/inference/msst_infer.py", line 74, in __init__
    self.model, self.config = self.load_model()
  File "/home//software/codes/MSST-WebUI/inference/msst_infer.py", line 106, in load_model
    model, config = get_model_from_config(self.model_type, self.config_path)
  File "/home//software/codes/MSST-WebUI/utils/utils.py", line 43, in get_model_from_config
    model = BSRoformer(
  File "<@beartype(modules.bs_roformer.bs_roformer.BSRoformer.__init__) at 0x7fc824e48f70>", line 97, in __init__
  File "/home//software/codes/MSST-WebUI/modules/bs_roformer/bs_roformer.py", line 392, in __init__
    Transformer(depth=time_transformer_depth, rotary_embed=time_rotary_embed, **transformer_kwargs)
  File "/home//software/codes/MSST-WebUI/modules/bs_roformer/bs_roformer.py", line 201, in __init__
    attn = Attention(dim=dim, dim_head=dim_head, heads=heads, dropout=attn_dropout,
  File "/home//software/codes/MSST-WebUI/modules/bs_roformer/bs_roformer.py", line 94, in __init__
    self.attend = Attend(flash=flash, dropout=dropout)
  File "/home//software/codes/MSST-WebUI/modules/bs_roformer/attend.py", line 62, in __init__
    device_properties = torch.cuda.get_device_properties(torch.device('cuda'))
  File "/home//.conda/envs/mss/lib/python3.10/site-packages/torch/cuda/__init__.py", line 523, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home//.conda/envs/mss/lib/python3.10/site-packages/torch/cuda/__init__.py", line 305, in _lazy_init
    raise RuntimeError(
**RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method**

**Comment by KitsuneX07** [comment]
请前往webui/msst.py line160
```
result_queue = multiprocessing.Queue()
    msst_inference = multiprocessing.Process(
        target=run_inference,
        args=(model_type, config_path, model_path, device, gpu_ids, output_format, use_tta, store_dict, debug, input_folder, result_queue),
        name="msst_inference"
    )
```
在result_queue=... 的上一行添加
```
multiprocessing.set_start_method('spawn')
```
希望这能解决你的问题

**Comment by iworldtong** [comment]
多谢大佬，问题解决了！(๑•̀ㅂ•́)و✧
