### ISSUE TITLE
建议：模型处理界面可调整输出的文件参数

### ISSUE THREAD

**Issue by YoMonNPC** [SUC-DriverOld/MSST-WebUI#34]
- [x] I have checked all the issues and the issue I raised has not been raised before.
- [x] I think the issue I raised is valuable rather than meaningless.

### Future request
添加调整输出音频的选项（如“音频格式转换”工具的输出设置）。

处理素材的时候发现输出的 wav 格式默认为 32 位采样率和双声道，体积接近原素材（mp4、mp3、m4a）的十倍。（明白是不同文件格式处理方式导致的）
希望模型处理输出的音频时能够自行选择采样率、声道数和位深度（比特率）。

**Comment by SUC-DriverOld** [comment]
感谢你的建议！
目前“小工具--音频格式转换”已经支持自定义选择输出详细格式。推理的话因为考虑到推理后的音频响度会超过0db，所以目前采用的是32位浮点格式来防止削波，后续会在设置页面中考虑添加全局音频格式设置
