### ISSUE TITLE
请问安装时报毒是怎么回事？怎么解决？

### ISSUE THREAD

**Issue by qiuqiao** [SUC-DriverOld/MSST-WebUI#37]
### Your operating environment
Windows系统： Windows 11 Version 23H2
安装的版本：1.6.2

### How to reproduce
双击安装程序，安装到如图所示的时候报毒：
![f29358ad8afc3e073eb2404ceb0f6c10](https://github.com/user-attachments/assets/dbdff733-160e-4f2a-8202-f20c27413b7d)

这是Windows安全中心里的记录：
![image](https://github.com/user-attachments/assets/a4d806f3-e048-4a01-82c0-ea21638f0acd)

点击“了解更多信息”，进入这个网页：https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.B!ml&threatid=2147735505

### Future request
希望能把导致报毒的部分去掉，能够成功安装

**Comment by SUC-DriverOld** [comment]
因为编译的exe没有签名，在windows defender面前一定会被拦。解决方法是关闭windows defender或者装一个火绒接管

**Comment by qiuqiao** [comment]
好的好的

**Comment by SUC-DriverOld** [comment]
以下是启动exe的c++源码，你可以自行尝试编译
```cpp
#include <iostream>
#include <windows.h>

void disable_quick_edit_mode() {
    HANDLE hInput = GetStdHandle(STD_INPUT_HANDLE);
    DWORD prev_mode;
    GetConsoleMode(hInput, &prev_mode);

    prev_mode &= ~ENABLE_QUICK_EDIT_MODE;
    SetConsoleMode(hInput, prev_mode);
}

int main() {
    disable_quick_edit_mode();

    system("chcp 65001 > nul");
    std::cout << R"(    __  _________________  _      __    __   __  ______)" << std::endl;
    std::cout << R"(   /  |/  / __/ __/_  __/ | | /| / /__ / /  / / / /  _/)" << std::endl;
    std::cout << R"(  / /|_/ /\ \_\ \  / /    | |/ |/ / -_) _ \/ /_/ // /  )" << std::endl;
    std::cout << R"( /_/  /_/___/___/ /_/     |__/|__/\__/_.__/\____/___/  )" << std::endl;
    std::cout << std::endl;
    std::cout << "Launching WebUI..." << std::endl;

    std::string command = ".\\workenv\\python.exe webUI.py";
    system(command.c_str());
    system("pause");

    return 0;
}
```

**Comment by qiuqiao** [comment]
确实，弹窗后，在windows安全中心点击操作-还原，再点弹窗的“重试”，就可以成功安装并运行了
