### ISSUE TITLE
Apollo模型推理音质反而下降，与Colab版本表现不同

### ISSUE THREAD

**Issue by qiuqiao** [SUC-DriverOld/MSST-WebUI#38]
### Your operating environment
1.6.2，Windows11，

### How to reproduce
Colab版本的Apollo MP3 Enhancer和MSST中的Apollo MP3修复模型，表现不一样，频谱看起来比较相似，但从人耳上来说，MSST推理出来的有明显的音质损失，包括合唱感和周期性的音量忽然下降。

Colab版本的地址：https://github.com/jarredou/Apollo-Colab-Inference?tab=readme-ov-file

输入音频：
[飞天(Input).zip](https://github.com/user-attachments/files/18010565/Input.zip)

**Comment by SUC-DriverOld** [comment]
MSST中的apollo推理代码直接使用的上游ZFTurbo的[Music-Source-Separation-Training](https://github.com/ZFTurbo/Music-Source-Separation-Training)中的代码，并未对其做修改。然后我个人也根据您的说法在本地和colab分别推理了一遍你提供的音频。

推理结果：https://alist.sucial.top/output.zip

推理参数如下：
使用模型：[pytorch_model.bin](https://huggingface.co/JusperLee/Apollo/resolve/main/pytorch_model.bin)（在colab中叫做MP3 Enhancer，在MSST中叫Apollo_LQ_MP3_restoration.ckpt）
chunksize：441000（10s）
overlap：4

得到的结果我试听下来倒是没有你所说的那些问题，将colab和local推理的结果进行反相位叠加后，可以抵消大部分音频，剩余的残留音频响度不超过-20db
![image](https://github.com/user-attachments/assets/5452f87b-691b-42ec-88d6-5b49a18b38a8)

colab上一共有三个apollo模型，其余两个更加新的模型我还没有加入到msst中。那两个模型效果确实更好一点。如果有更多疑问的话，可以尝试使用上游ZFTurbo的[Music-Source-Separation-Training](https://github.com/ZFTurbo/Music-Source-Separation-Training)进行分离测试。向ZFTurbo反馈问题可以前往：https://discord.gg/P7FhQFH

**Comment by qiuqiao** [comment]
看来是我自己的问题，可能是没有真正成功安装。
