### ISSUE TITLE
每次涉及到点击选择文件夹的操作，程序就会报错。

### ISSUE THREAD

**Issue by bearcolin** [SUC-DriverOld/MSST-WebUI#39]
我是 macOS 在 terminal 运行的，每次在 webui 点击选择文件夹的时候，Python 程序就崩了报错。

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow should only be instantiated on the main thread!'

**Comment by bearcolin** [comment]
<img width="1244" alt="截屏2024-12-05 10 19 07" src="https://github.com/user-attachments/assets/68698c7c-bb61-455c-97c4-3f2098508096">

**Comment by SUC-DriverOld** [comment]
这个问题是由于macOS的GUI相关操作必须在主线程中执行，然而，项目使用的是Gradio来搭建网页，Gradio会在后台为每个组件和函数启动独立的线程。这就导致了上述的问题。我能在mac中复现此问题，但遗憾的是目前没有非常好的解决方法（要同时兼顾Linux和Windows）。该问题涉及到上游的thinker和gradio。
**现阶段的解决方法是：在输出目录文本框里直接输入路径而不要使用“选择文件夹”按钮。**
![image](https://github.com/user-attachments/assets/3e32df0c-2786-4c3c-b05a-718d77fe01af)
