### ISSUE TITLE
It doesn't recognize the gpu.

### ISSUE THREAD

**Issue by kbuwel** [SUC-DriverOld/MSST-WebUI#40]
I have 2 PCs.
I set up almost the same PC environment.
CUDA 12.1 cudnn 9.4
The differences are as follows.
PC 1 has 2 rtx3060 12gb.
PC 2 has 1 gtx1660.
I completed the installation as instructed in the README.md file.
The problem is that it does not recognize rtx3060 and only works with cpu.
There is no button or item to select rtx3060.
GTX1660 is recognized.

**Comment by SUC-DriverOld** [comment]
Please try updating your graphics card driver.

**Comment by kbuwel** [comment]
I have the following drivers installed on both systems, are they affected?
555.99-desktop-win10-win11-64bit-international-nsd-dch-whql
If it's affected by the driver, then the gtx1660 shouldn't be recognized either, and should only work with the cpu, which I don't understand.

**Comment by SUC-DriverOld** [comment]
I use `torch.cuda.is_available()` to check if your device supports GPU. You can go to the Python environment of the project and follow [this tutorial](https://stackoverflow.com/questions/48152674/how-do-i-check-if-pytorch-is-using-the-gpu/) to test it.
