### ISSUE TITLE
webUI_for_clouds.py多出了一个参数导致在colab上使用时错误

### ISSUE THREAD

**Issue by juzi5201314** [SUC-DriverOld/MSST-WebUI#47]
https://github.com/SUC-DriverOld/MSST-WebUI/blob/main/tools/webUI_for_clouds/webUI_for_clouds.py#L79 往下4个函数调用都多出了`is_audio=True`, 删除这4处即可正常使用.

**Comment by SUC-DriverOld** [comment]
感谢指出，已在最新的[commit](https://github.com/SUC-DriverOld/MSST-WebUI/commit/4dd354f7e0269856010ce9b1e47eea64d2a5007a)中修复~
